//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InfWizard.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Last_SaveDirectory {
            get {
                return ((string)(this["Last_SaveDirectory"]));
            }
            set {
                this["Last_SaveDirectory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Last_CreateDriverDirectory {
            get {
                return ((bool)(this["Last_CreateDriverDirectory"]));
            }
            set {
                this["Last_CreateDriverDirectory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://sites.google.com/site/libusbdotnet/driver_resources/DriverResourceDownload" +
            "s.xml?attredirects=0&d=1")]
        public string DriverResourceUrl {
            get {
                return ((string)(this["DriverResourceUrl"]));
            }
            set {
                this["DriverResourceUrl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection UserDeviceManufacturers {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["UserDeviceManufacturers"]));
            }
            set {
                this["UserDeviceManufacturers"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection UserDeviceInterfaceGUIDs {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["UserDeviceInterfaceGUIDs"]));
            }
            set {
                this["UserDeviceInterfaceGUIDs"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection UserDeviceDescriptions {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["UserDeviceDescriptions"]));
            }
            set {
                this["UserDeviceDescriptions"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection UserSaveDirectorys {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["UserSaveDirectorys"]));
            }
            set {
                this["UserSaveDirectorys"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Last_DriverName {
            get {
                return ((string)(this["Last_DriverName"]));
            }
            set {
                this["Last_DriverName"] = value;
            }
        }
    }
}
