name: build
on:
  push:
    branches:
      - v2
  pull_request:

jobs:
  libusbdotnet_windows:
    runs-on: windows-2022

    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
          ref: 'v2'

      - uses: actions/setup-dotnet@v5
        with:
          dotnet-version: '8.0.x'

      - name: Build
        run: dotnet build .\stage\LibUsbDotNet\LibUsbDotNet.csproj -c Release
      
      - name: Pack       
        run: dotnet pack .\stage\LibUsbDotNet\LibUsbDotNet.csproj -c Release -o ${{ github.workspace }}/nuget/

      - name: Upload LibUsbDotNet NuGet package
        uses: actions/upload-artifact@v7
        if: always()
        with:
          name: LibUsbDotNet-${{ github.run_id }}
          path: '${{ github.workspace }}/nuget/' 

  libusbdotnet_macos:
    runs-on: macos-15

    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - uses: actions/setup-dotnet@v5
        with:
          dotnet-version: '8.0.x'

      - name: Build
        run: dotnet build ./stage/LibUsbDotNet/LibUsbDotNet.csproj -c Release

  libusbdotnet_ubuntu:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
          ref: 'v2'

      - uses: actions/setup-dotnet@v5
        with:
          dotnet-version: '8.0.x'

      - name: Install libusb
        run: |
          sudo apt-get update
          sudo apt-get install -y libusb-1.0-0

      - name: Build
        run: dotnet build ./stage/LibUsbDotNet/LibUsbDotNet.csproj -c Release
