name: docs
on:
  push:
    branches:
      - master

permissions:
  contents: read

jobs:
  generate-docs:

    runs-on: windows-latest

    permissions:
      contents: write # To push docs to the gh-pages branch

    steps:
      - uses: actions/checkout@v7

      - name: Setup .NET 8.0
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 8.0.x

      - name: Setup DocFX
        run: dotnet tool install -g docfx

      - name: Navigate
        run: cd ..
        
      - name: DocFX Build
        working-directory: docfx_project
        run: docfx .\docfx.json
        continue-on-error: false

      - name: Navigate
        run: cd ..
        
      - name: Publish
        if: github.event_name == 'push'
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docfx_project/_site
          force_orphan: true
